### ISSUE TITLE
MessageEngine Bug Report

### ISSUE THREAD

**Issue by fbtoolo** [afkvido-development/MessageEngine-PTB#4]
KEEP IN MIND THAT MESSAGEENGINE IS STILL IN ALPHA TESTING. EXPECT BUGS TO COME OUT FREQUENTLY AND BE FIXED FREQUENTLY.

**Describe the bug**

**Steps to reproduce the bug**
Include commands, accounts, etc.
1.
2.
3.
4.

**Expected behavior**
what should happen instead

**Screenshots**
please add a screenshot so i can see

**Additional context**

**Comment by afkvido** [comment]
How may I help you?
